// src/styles/themeStyles.js

export const getSharedStyles = (theme) => ({
  backButtonStyle: {
    background: 'transparent',
    border: 'none',
    color: theme.brand,
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 0',
    outline: 'none',
    WebkitTapHighlightColor: 'transparent',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    transition: 'opacity 0.2s ease',
  },
  inputStyle: {
    width: '100%',
    boxSizing: 'border-box',
    border: theme.border,
    background: '#FFFBF2',
    color: theme.text,
    borderRadius: theme.radius || '10px',
    padding: '13px 16px',
    fontSize: '13.5px',
    outline: 'none',
    fontFamily: 'inherit',
    transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
    boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.02)',
    WebkitTapHighlightColor: 'transparent',
  },
  actionButtonStyle: {
    backgroundColor: theme.buttonBg || theme.brand,
    color: theme.buttonText || '#FFFFFF',
    border: 'none',
    fontWeight: '700',
    cursor: 'pointer',
    textAlign: 'center',
    outline: 'none',
    WebkitTapHighlightColor: 'transparent',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
    boxShadow: '0 4px 14px rgba(225, 112, 85, 0.2)',
  },
  secondaryButtonStyle: {
    backgroundColor: 'transparent',
    color: theme.text,
    border: theme.border,
    fontWeight: '600',
    cursor: 'pointer',
    textAlign: 'center',
    outline: 'none',
    WebkitTapHighlightColor: 'transparent',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  accordionHeaderStyle: {
    border: theme.border,
    background: theme.bg,
    borderRadius: theme.radius || '10px',
    padding: '12px 16px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    boxSizing: 'border-box',
    width: '100%',
    outline: 'none',
    WebkitTapHighlightColor: 'transparent',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    transition: 'background 0.2s ease',
  }
});